# Generated by Django 5.0.7 on 2024-08-09 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["created_at"]},
        ),
        migrations.RemoveField(
            model_name="order",
            name="total_amount",
        ),
        migrations.AddField(
            model_name="order",
            name="city",
            field=models.CharField(default="d", max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="postal_code",
            field=models.CharField(default="d", max_length=20),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="orders.order",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1, verbose_name="Quantity"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["-created_at"], name="orders_orde_created_f0ce29_idx"
            ),
        ),
    ]
