# Generated by Django 5.0.7 on 2024-08-09 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_order_city_alter_order_postal_code"),
        ("users", "0008_clientdetails"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="user",
        ),
        migrations.AddField(
            model_name="order",
            name="client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="client_details",
                to="users.clientdetails",
                verbose_name="client",
            ),
        ),
    ]
