# Generated by Django 5.0.7 on 2024-08-09 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_remove_order_user_order_client"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="city",
        ),
        migrations.RemoveField(
            model_name="order",
            name="postal_code",
        ),
    ]
