# Generated by Django 5.0.7 on 2024-08-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_alter_category_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AddField(
            model_name="category",
            name="short_description",
            field=models.CharField(max_length=512, null=True),
        ),
    ]
