# Generated by Django 5.0.7 on 2024-08-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_alter_category_short_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(null=True, unique=True),
        ),
    ]
