# Generated by Django 5.0.7 on 2024-08-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_alter_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
