# Generated by Django 5.0.7 on 2024-08-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0010_product_available"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["name"]},
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["id", "slug"], name="product_pro_id_b9e5a0_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["name"], name="product_pro_name_b60cd1_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["-created_at"], name="product_pro_created_22b186_idx"
            ),
        ),
    ]
