# Generated by Django 5.0.7 on 2024-08-08 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0011_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-created_at"]},
        ),
    ]
