# Generated by Django 5.0.7 on 2024-08-08 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_cart"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="product",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="user",
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
        migrations.DeleteModel(
            name="CartItem",
        ),
    ]
