# Generated by Django 5.0.7 on 2024-08-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(default="Customer", max_length=256),
        ),
    ]
