# Generated by Django 5.0.7 on 2024-08-09 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_feedbacks"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="your first name",
                        max_length=100,
                        verbose_name="first name",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="your last name",
                        max_length=100,
                        verbose_name="last name",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        help_text="region", max_length=100, verbose_name="region"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        help_text="city", max_length=100, verbose_name="city"
                    ),
                ),
                ("street", models.TextField(help_text="street", verbose_name="street")),
                (
                    "flat_number",
                    models.IntegerField(
                        blank=True,
                        help_text="flat number",
                        null=True,
                        verbose_name="flat number",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_details",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "client detail",
                "verbose_name_plural": "client details",
                "db_table": "client_details",
            },
        ),
    ]
